import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Naufal Fikri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.splashimg}>
          <img src="/madebymygf.png" width="300px"/>
        </div>

        <h1>Naufal Fikri</h1>
        <p>Hello there,</p>
        <p>I am Naufal. Melbourne based computer science educator, software engineer, and automation hobbyist.</p>
        <p>I am a software engineer at InGenious AI. Formerly a teaching and research assistant University of Melbourne.</p>
        <p>Majority of the site is under renovation! It may be a little less friendly for the mobile friends, sorry about that.</p>
      
        <span>((links here ty))</span>
      </main>

      <footer className={styles.footer}>
        <p> (c) Naufal Fikri Setiawan / 2016-2021</p>
      </footer>
    </div>
  )
}

export default Home
